spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:gamecenter@cluster0.0g1ue.mongodb.net/gamecenter?retryWrites=true&w=majority
      database: gamecenter
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000